### ISSUE TITLE
Some questions for the pipeline

### ISSUE THREAD

**Issue by WangZhe1026** [pvnieo/SNK#1]
After reading the paper, I have a question: Why is it called axiomatic method and why is it called zero-shot. Because the pipeline still uses a FM solver and the prism energy is just used to modify p2p map created by FM solver and the FM solver needed to train I think. 
    And another question about Reconstruction part in the pipeline : the loss.py is used **in Reconstruction part** to calculate the energy as the loss?
    So, if I want to train a network using this pipeline, I should do a forward computation of FM and prism(using that decoder.py) respectively, then when calculate the loss, compute the L =λmseLmse +λfmapLfmap +λcycleLcycle + λprimoLprimo, then backward, is this a correct description for the pipeline?
     Thank you if you can help me solve these questions.

**Comment by pvnieo** [comment]
Hi @WangZhe1026 

The response to your question will be long in here. Can you please send me an email?

**Comment by WangZhe1026** [comment]
@pvnieo Thank you,  you can email me at yenaibangbing [at] gmail [dot] com.
