### ISSUE TITLE
abuout some question

### ISSUE THREAD

**Issue by zzifer** [pvnieo/SNK#2]
Thanks for your contribution. I have some questions after reading the article. The first one is, is the diffusionnet used in the article the same one, or do they share parameters? Or are they different? The second question is, how are the latent code and source shape combined? Is it just concatenating two vectors, such as (x, y, z, l)? The third question is, after the latent code and source shape are combined, they will enter the diffusionnet. Does the diffusionnet here only generate the features of the source shape? Will it process the latent code l?Looking forward to your answer.

**Comment by pvnieo** [comment]
thank you for your interest.

1- the diffusion net used for the "feature extractor" module (refer to fig 1), is the same, it's applied in a siamese way to both shapes. The diffusion net that is used in the prism decoder is a different diffusion net
2- the latent code is duplicated and concatenated with the XYZ coordinates, and then to the diffusion net
3- yes, diffusionnet in the prism decoder only generates features on the source, which then will be used to predict the rotations and the translations

closing the issue, feel free to re-open it if you still have some additional questions

**Comment by zzifer** [comment]
@pvnieo Thank you for your quick reply. I do have some questions. In addition to the Feature extractor module, DiffusionNet is used in both encode and decode. Are there any other changes in the diffusion in these two places except that the output dimension is different from the Feature extractor module? In addition, can you provide the specific content of batch in the code def forward(self, batch)? I want to know its format and the meaning of the corresponding parameters,  otherwise it will be difficult for me to make changes.

**Comment by pvnieo** [comment]
@zzifer No, only the input and output dimensions are different, the rest of the architecture is the same.

batch is a `torch_geometric.data.Data` object, that contains the pos (xyz), faces, and the diffusion net operators, please have a look here for inspiration (https://github.com/pvnieo/diffusion-net-plus), otherwise, I'm working on releasing the full implementation soon!

**Comment by zzifer** [comment]
Thank you for your reply, and I look forward to your complete code.
