### ISSUE TITLE
DiffusionNet used in prism_decoder.py

### ISSUE THREAD

**Issue by HadassaMB** [pvnieo/SNK#3]
Hi,

Can you provide the code of the DiffusionNet model used in your implementation in prism_decoder.py ? The DiffusionNet available in [git ](https://github.com/nmwsharp/diffusion-net/tree/master) is supposed to receive 3D coordinates and a mass function, but in your implementation it only gets batch. If you are using this implementation, can you provide an example on how to use it ? 

Thank you in advance.

**Comment by pvnieo** [comment]
Hi @HadassaMB 

You should try something similar to what it's used here: https://github.com/pvnieo/diffusion-net-plus
I'm working on releasing the full implementation, meanwhile, I can answer all your questions!

**Comment by pvnieo** [comment]
please feel free to reopen the issue if you have any questions!
